[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."
  # command = ". build.sh"
  
[build.environment]
  HUGO_VERSION = "0.92.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"